---
title: STEM for the Streets
baseurl: "/"
permalink: "/:title/"
color_scheme: light
accent_color: ''
header:
  title: STEM for the Streets
  has_nav: true
  logo_img: "/images/SFTS Logo.JPG"
footer:
  content: "&copy; Stackbit-Exto. All rights reserved."
  links:
  - text: Made with Stackbit
    url: https://www.stackbit.com
    new_window: true
  has_social: true
sass:
  indentWidth: 4
  style: nested
  precision: 10
plugins:
- jekyll-menus
exclude:
- Gemfile
- Gemfile.lock
- node_modules
- vendor/bundle/
- vendor/cache/
- vendor/gems/
- vendor/ruby/
- ssg-build.sh
- LICENSE.md
- README.md
- netlify.toml
- stackbit-build.sh
- stackbit-pull.js
collections:
  posts:
    permalink: "/posts/:title/"
